// import { Metadata } from "next";

import { AdminSidebar } from "@/components/shared";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

// export const metadata: Metadata = {
//   title: "AuthLayout",
//   description: "Generated by create next app",
// };

export default function Homelayout(
  { children }: { children: React.ReactNode }
) {
  return (
    <SidebarProvider>
      <AdminSidebar />
      <main className="w-full bg-[#3F3F1]">
        <div className="px-3">
          <SidebarTrigger />
        </div>
        {children}
      </main>
    </SidebarProvider>
  )
}
